apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.Global.Namespace }}
  labels:
    app: mhwebui
data:
  myvalue: "Hello World"
  image-name: {{ .Values.Deployment.ImageName | quote}}