apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhwebui-deployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80