apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhwebui-deployment
  namespace: {{ .Values.Global.Namespace }}
  labels:
    app: mhwebui
spec:
  replicas: {{ .Values.Deployment.Replicas }}
  selector:
    matchLabels:
      app: mhwebui-label
  template:
    metadata:
      labels:
        app: mhwebui-label
    spec:
      containers:
      - name: mhwebui
        image: tushark1704/mh-web-ui:0.0.1
        ports:
        - containerPort: 3000